server {
    listen 80;

    location / {
        # 'backend' és el nom del servei que posarem al docker-compose.yml
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
