{
 "title": "GreenDevCorp - Overview",
 "tags": [ "greendev" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pods running per namespace",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"greendev.*\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU usage per pod",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"greendev.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"greendev.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP requests/s",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  }
 ]
}