apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # AQUI UTILITZA LA IMATGE QUE VAS PUJAR ABANS!
        image: paucabestany/python-app-gsx:v2
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: greendev-config
        resources: # Limits de seguretat
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe: # Prova de salut (El "metge")
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
